version: "3.8"

services:
  store:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes: 
      - ./redis-data:/data
  
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes: 
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build:
      context: ../server
    depends_on:
      - database
      - store
    ports:
      - "5000:5000"
