version: "3.8"

services:
    store:
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./redis-data:/data

    database:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_DB=$POSTGRES_DATABASE
        volumes:
            - ./pg-data:/var/lib/postgresql/data
            - ../server/price-action/database-setup:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"

    server:
        build:
            context: ../server
            dockerfile: dev.Dockerfile
        volumes:
            - ../server:/trade/server
            - /trade/server/node_modules
        depends_on:
            - database
            - store
        ports:
            - "5000:5000"

    api-database:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=$PG_API_PASS
            - POSTGRES_USER=$PG_API_USER
            - POSTGRES_DB=$PG_API_DB
        volumes:
            - ./api-pg-data:/var/lib/postgresql/data
            - ../server/api/database-setup:/docker-entrypoint-initdb.d
        ports:
            - "5433:5432"

    client:
        build:
            context: ../client
            dockerfile: Dockerfile
        volumes:
            - ../client:/trade/client
            - ../client/node_modules:/trade/client/node_modules
        ports:
            - "3000:3000"
