version: "3.8"

services:
  store:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes: 
      - ./redis-data:/data
  
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes: 
      - ./pg-data:/var/lib/postgresql/data
      - ../server/price-action/database-setup/ticker.sql:/docker-entrypoint-initdb.d/2_ticker.sql
    ports:
      - "5432:5432"
  server:
    build:
      context: ../server
      dockerfile: dev.Dockerfile
    volumes:
      - ../server:/trade/server
    depends_on:
      - database
      - store
    ports:
      - "5000:5000"
